---
swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /v1.0

consumes:
  - application/json
produces:
  - application/json

definitions:
  LocationUploadRequest:
    description: Upload location request
    type: object
    required:
      - userId
      - latitude
      - longitude
    properties:
      userId:
        type: string
        description: Google user's unique identifier
        example: "108032329945935107776"
      latitude:
        type: number
        format: double
        minimum: -90
        maximum: 90
        description: Client latitude
        example: -77.0364
      longitude:
        type: number
        format: double
        minimum: -180
        maximum: 180
        description: Client longitude
        example: 38.8951
  LocationUploadResponse:
    description: Upload location response
    type: object
    properties:
      code:
        type: string
        description: Server status code
        example: "OK"
      message:
        type: string
        description: Server response
        example: "Location uploaded"
      userId:
        type: string
        description: Google user's unique identifier
        example: "108032329945935107776"

paths:
  /location:
    post:
      summary: Upload location
      description: Upload user's current location
      parameters:
        - name: location_request
          in: body
          schema:
            $ref: '#/definitions/LocationUploadRequest'
      responses:
        200:
          description: Location uploaded
          schema:
            type: object
            $ref: '#/definitions/LocationUploadResponse'
